// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LampLib.Models
{
    [Table("Lamp")]
    public partial class Lamp
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string DeviceName { get; set; }
        [Column("TurnedON", TypeName = "datetime")]
        public DateTime TurnedOn { get; set; }
        public int Watt { get; set; }
        public int TurnOnDuration { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        [Required]
        [StringLength(50)]
        public string Country { get; set; }
    }
}